import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/index.module.css'
import Home from './home'

export default function Index() {
  return (
    <div className={styles.container}>
      <Head>
        <title>ASHABB MyBlog Nextjs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="next, nexttrip, trip, react, node, ashabb" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <footer className={styles.footer} >
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
