import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/index.module.css'
import Home from './home'

export default function Index() {
  return (
    <div className={styles.container}>
      <Head>
        <title>ASHABB MyBlog Nextjs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="next, nexttrip, trip, react, node, ashabb" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <footer className={styles.footer} >
        <a
          href="https://ashabb-myblog-nextjs.vercel.app/"
          target="_blank"
          rel="noopener noreferrer"
        >
          live link - https://ashabb-myblog-nextjs.vercel.app/
        </a>
      </footer>
    </div>
  )
}
